### ISSUE TITLE
Add search endpoint

### ISSUE THREAD

**Issue by jsdir** [martinshkreli/shchem#11]
depends on #10 

- `GET /api/v1/compounds?query={query}`
- returns a json response with a list of compounds

**Comment by jsdir** [comment]
@gabelerner #10 has a list of properties that we are going to initially index.

**Comment by gabelerner** [comment]
should we have one field that searches all props or a list of one field per prop or the former + open up advanced search to the latter?

**Comment by jsdir** [comment]
For now, let's just have one field that searches all props. I'll create an issue for an advanced search.
